export enum PermissionResource {
  ANY = '*',
  BANNER = 'banners',
  BLOG = 'blogs',
  CATEGORY_BLOG = 'categories-blog',
  CONTACT = 'contacts',
  HISTORY = 'histories',
  IMAGE = 'images',
  TRAINER = 'trainers',
  VIDEO = 'videos',
  INFO_WEBSITE = 'info-websites',
  LEAD = 'leads',
  MENU = 'menus',
  PERMISSION = 'permissions',
  SERVICE_PACKAGE = 'service-packages',
  SERVICE_CATEGORY = 'service-categories',
  USER = 'users',
  FEEDBACK = 'feedbacks',
}
