export enum Routes {
  AUTH = 'auth',
  AUTH_GOOGLE = 'auth/google',
  USERS = 'users',
  IMAGE = 'images',
  VIDEO = 'videos',
  BLOG = 'blog',
  CATEGORIES_BLOG = 'categories-blog',
  CONTACTS = 'contacts',
  LEADS = 'leads',
  BANNER = 'banner',
  SERVICE_PACKAGE = 'service-packages',
  SERVICE_CATEGORY = 'service-categories',
  TRAINER = 'trainers',
  INFO_WEBSITE = 'info-website',
  ROLES = 'roles',
  PERMISSIONS = 'permissions',
  FEEDBACK = 'feedbacks',
}

export enum Services {
  AUTH = 'AUTH_SERVICE',
  USERS = 'USERS_SERVICE',
  SESSION = 'SESSION_SERVICE',
  MAILER = 'MAILER_SERVICE',
  MAILS = 'MAILS_SERVICE',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD_SERVICE',
  AUTH_GOOGLE = 'AUTH_GOOGLE_SERVICE',
  IMAGE = 'IMAGE_SERVICE',
  ROLES = 'ROLES_SERVICE',
}
